name: Feature Request
description: Suggest an idea for this project
title: "[Feature]: "
labels: [enhancement, triage]
assignees:
  - Power-Maverick
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to provide an enhancement idea for the tool!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. Twitter handle, LinkedIn profile, email@example.com
    validations:
      required: false
  - type: textarea
    id: new
    attributes:
      label: What feature would you like to add?
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Any idea or solution you propose?
    validations:
      required: false
